sudo: required
services:
    - docker

before_install:
  - docker build -t richardgohcr/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true richardgohcr/react-test npm test

after_success:
  - docker build -t richardgohcr/multi-client ./client
  - docker build -t richardgohcr/multi-nginx ./nginx
  - docker build -t richardgohcr/multi-server ./server
  - docker build -t richardgohcr/multi-worker ./worker
  #Log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push richardgohcr/multi-client
  - docker push richardgohcr/multi-nginx
  - docker push richardgohcr/multi-server
  - docker push richardgohcr/multi-worker
